### ISSUE TITLE
Remove automatic armor for CTs

### ISSUE THREAD

**Issue by jgh713** [hlstriker/SMPlugins#1]

**Comment by jgh713** [comment]
Alongside this change, revert healthshot healing back to 50.

**Comment by SZOKOZ** [comment]
I'm guessing this is still a thing. Is this an approved idea?

**Comment by RussianRonin** [comment]
Honestly, no. Just the healthshot thing which is a very easy fix lol.

**Comment by SZOKOZ** [comment]
`healthshot_health`
I'm sure this cvar is already known to you russian since it was changed from the default 50.

**Comment by RussianRonin** [comment]
It is.
