### ISSUE TITLE
Respawns and Rtv

### ISSUE THREAD

**Issue by jgh713** [hlstriker/SMPlugins#11]
RTV kills the respawn bot, but that does very little to help when on a TP map. There should either be an admin command (lead+) or have the map auto-rtv without waiting for round-end if the bot has not died as of yet (which could be problematic if it's a map with particularly long respawn timers, in the 3-5 minute ranges, getting rtv'd early). I'm leaning towards the former.

**Comment by hlstriker** [comment]
This can already be toggled on a per map basis via a config file. The ForceMapEnd plugin has sv_forcemapend_waitonroundend which is set to 0 when you want the map to change instantly. Many of the course maps already have this set.

https://github.com/hlstriker/SMPlugins/blob/master/Plugins/ForceMapEnd/ForceMapEnd.sp#L32
