### ISSUE TITLE
No-knife speed

### ISSUE THREAD

**Issue by jgh713** [hlstriker/SMPlugins#16]
Players move at 260u/s when they drop their knife. Needs to be changed to 250, or universal 260, with a record wipe at some point in the future. Possibly better to wait for other issues to be fixed, then do a global record wipe.

**Comment by hlstriker** [comment]
Just tested and it is 250 without a knife. Something might have bugged when you saw it at 260 so it's worth keeping an eye on.

**Comment by hlstriker** [comment]
From our conversation in discord you were looking at cl_showpos which displays the incorrect speed in this case. Closing this issue.
