### ISSUE TITLE
Day: Purge Warday

### ISSUE THREAD

**Issue by jgh713** [hlstriker/SMPlugins#18]
You cant see anyone but yourself for 60 seconds. Everyone starts with a pistol. Cant pick up weps till the 60 seconds is over. Armory will be a clusterfuck, or you can go off and hide.

**Comment by RussianRonin** [comment]
Make teamdamage enabled too?

**Comment by SZOKOZ** [comment]
Approved? 
This is a free for all day right?

**Comment by RussianRonin** [comment]
Yes and Yes.
