### ISSUE TITLE
Day: Menu Freeday

### ISSUE THREAD

**Issue by jgh713** [hlstriker/SMPlugins#19]
Give each player access to a freeday menu, allowing them toggles for:

 - Speed (high and low)
 - Gravity (low and zero)
 - Autohop
 - Invincibility(?)
 - Noclip(?)
 - Teleport to cells(?)

Unsure about the (?) ones.

**Comment by jgh713** [comment]
Possibly a shorter round as well. 5-7 minutes?

**Comment by SZOKOZ** [comment]
Approved?

**Comment by RussianRonin** [comment]
Yes
