### ISSUE TITLE
LR Effect: Autobhop

### ISSUE THREAD

**Issue by jgh713** [hlstriker/SMPlugins#22]

**Comment by RussianRonin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LR Auto-Bhop](https://trello.com/c/jL5JpkRW/2-lr-auto-bhop)

**Comment by wasyady** [comment]
unavailable

**Comment by RussianRonin** [comment]
Yeah. I was just testing things.

**Comment by SZOKOZ** [comment]
Approved?
