### ISSUE TITLE
Notify talking while muted

### ISSUE THREAD

**Issue by jgh713** [hlstriker/SMPlugins#23]
When people are attempting to use their mic whlile muted, either due to admin mute, being dead on JB, etc, there should be a chat notification (max 1/sec?).

**Comment by hlstriker** [comment]
This should be easy enough making a new plugin that uses the squelch manager API.

https://github.com/hlstriker/SMPlugins/blob/master/Libraries/SquelchManager/squelch_manager.inc#L24
