### ISSUE TITLE
Zombie warday should do damage when speed ticks

### ISSUE THREAD

**Issue by jgh713** [hlstriker/SMPlugins#36]
20 health damage, possibly. Five ticks and the warday's over. Prevents delaying by Ts and keeps the wardays to a reasonable length.

**Comment by RussianRonin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zombie Tick Damage](https://trello.com/c/qoQL1HPu/1-zombie-tick-damage)

**Comment by SZOKOZ** [comment]
Explanation in greater detail needed.
Approved?
Assigned to ruski or me?

**Comment by RussianRonin** [comment]
I got this.
