### ISSUE TITLE
Weapon Selection changes

### ISSUE THREAD

**Issue by jgh713** [hlstriker/SMPlugins#4]
So, Weapon Selection is awful. Potential solutions are as follows. Needs to be discussed which (possibly multiple) should be used.

- Allow the warden to choose gun category (i.e. rifles, snipers only, smgs, shotguns, heavy, pistols, etc), and have individuals choose their weapon.
 - Remove Warden choice, allow players to buy
 - Allow Warden to enable/disable by slot (i.e. primaries only, no pistols, grenades enabled), then have players buy within those guidelines
 - Allow individuals to select their weapons from a predefined list of loadouts

**Comment by SZOKOZ** [comment]
Is this a special day? Not sure I quite understand this.

**Comment by RussianRonin** [comment]
So there is a weapon selection warday in which the warden selects which weapon everyone will use for that warday.

I would want it changed so that the warden selects a weapon category and the t's select a weapon from that category.

**Comment by SZOKOZ** [comment]
Ohhh, okay, I understand. 
`I would want it changed so that the warden selects a weapon category and the t's select a weapon from that category.`
Approved?

**Comment by RussianRonin** [comment]
Yes

**Comment by SZOKOZ** [comment]
Will test my code in the evening and document it. 
-Early morning for me. Sleep cycled messed up-
