### ISSUE TITLE
Prestrafe in start zone?

### ISSUE THREAD

**Issue by e-slut** [hlstriker/SMPlugins#55]
It caps your speed inside the start zone to 250u/s and you are unable to prestafe.

**Comment by SZOKOZ** [comment]
By default yes, we would need a prestrafe style to enable a player to prestrafe in the start zone.

**Comment by hlstriker** [comment]
> we would need a prestrafe style to enable a player to prestrafe in the start zone.

Already exists:
https://github.com/hlstriker/SMPlugins/blob/master/Plugins/MovementStyles/Style_NoSpeedCap.sp

**Comment by SZOKOZ** [comment]
Hmm, then I haven't seen it in game either. I'll double check.

**Comment by SZOKOZ** [comment]
Oh... that has no implementation. I think...
In any case I don't see it as a style choice on bhop.

**Comment by hlstriker** [comment]
> Oh... that has no implementation.

It's just hacky due to the way things were changed around while making the speed run plugin. See here: https://github.com/hlstriker/SMPlugins/blob/master/Mods/SpeedRuns/SpeedRuns_Core.sp#L1233

There should really be a forward there instead that other plugins can hook and return >= plugin_handled. Wasn't a high priority to change though.

**Comment by SZOKOZ** [comment]
Then it's probably just disabled on server due to a missing dependency maybe? hmm -Asks server owner-

**Comment by hlstriker** [comment]
> Then it's probably just disabled on server due to a missing dependency maybe? hmm -Asks server owner-

Not all of the servers run every style. I think that plugin is only on the surf server right now.

**Comment by SZOKOZ** [comment]
@e-slut Well there's your answer. Make a suggestion on Swoobles to enable the style on bhop. GL

**Comment by HymnsForDisco** [comment]
Prestrafing in start is disabled on maps where the speedcap is 250 in start zone (most on Bhop).  The speedcap code could be changed to allow up to 280u/s while on the ground no matter the cap
