### ISSUE TITLE
Issue with  some sql tables.

### ISSUE THREAD

**Issue by lilgay** [hlstriker/SMPlugins#68]
hello i was interested  try to learn to make an new styles  for timer plugin  no erros in server logs from tables Database core works fine but i had problem to install some tables for example  plugin_zonemanager_data i get this error  https://i.imgur.com/iTxukp3.png also core_servers doesnt list my private server id from config cfg/swoobles.  Can someone dumb for me  clean working tables? I Love your servers.

I'm using MySQL 5.7.22

**Comment by hlstriker** [comment]
> also core_servers doesnt list my private server id from config cfg/swoobles.

You have to manually create a row in core_servers and use the server_code for the value in database_servers.cfg

As for the error in your screenshot I'm not sure. Make sure you are compiling using the compiler included in this repo or try a different version of MySQL (I recommend MariaDB as a drop in replacement for MySQL).

**Comment by lilgay** [comment]
About compiling. Script couldn't find patches for files some reason. I just draged in from sm 1.9 compile.exe and compiled without problems. I Also  had problem with adding  rows manual.  I got this error- rows doesn't have a default  value.  I will give a try with MariaDB

**Comment by hlstriker** [comment]
There is a file called **compile_script.bat** included in the compile directory for this repo. You can edit the COMPILER and OUTPUT variables of the file and then simply use that batch file to drag and drop a single plugin or an entire folder on top of the batch file for it to compile whatever you dropped.

 https://github.com/hlstriker/SMPlugins/blob/master/_SourceMod%201.6%20Compiler/compile_script.bat

If the plugin is having problems finding headers, that means you didn't leave the file in the directory it came in. You should just download the entire repo and leave all the files where they are so things can compile correctly.

> I Also had problem with adding rows manual. I got this error- rows doesn't have a default value.

See the second answer here to fix that: https://stackoverflow.com/questions/15438840/mysql-error-1364-field-doesnt-have-a-default-values

**Comment by lilgay** [comment]
Yep i compiled everything with your script still no success
2.
I don't have  in  my sql_mode  line STRICT_TRANS_TABLES . 
only this - NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
 btw im running mysql db at debian 9 and now i switched to MariaDB 10.1.26.  Anyway i still get same error - /* SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '%i, %i, %i, %i, '%s', %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %i, %i, %i' at line 4 */
/* Affected rows: 0  Found rows: 0  Warnings: 0  Duration for 1 of 2 queries: 0,047 sec. */
and when i write !zm i get this error.
[SM] Please wait for the zones to finish loading from the database.

**Comment by hlstriker** [comment]
Delete all your SourceMod error log files, then restart your server. If a new error log is created you can copy/paste it here so I can take a look.

**Comment by lilgay** [comment]
there was 1 not related error with your plugins that i fixed. same issue. At start when i had missings files for zone manager it did write  error that thing is missing or not when i wrote !zm

plugin list:

sm plugins list
[SM] Listing 63 plugins:
  01 "Command List" (1.0) by hlstriker
  02 "API: Client Cookies" (1.9) by hlstriker
  03 "Map Stats" (1.1) by hlstriker
  04 "Zone Type: Teleport" (1.3) by hlstriker
  05 "API: Database Map Stats" (1.5) by hlstriker
  06 "Fix Round End Classnames" (1.0) by hlstriker
  07 "API: Entity Hooker" (1.9) by hlstriker
  08 "Disable duck delay" (1.1) by hlstriker
  09 "Spectate Menu" (1.3) by hlstriker
  10 "API: Database Map Sessions" (1.5) by hlstriker
  11 "API: Database Servers" (1.4) by hlstriker
  12 "Fun Commands" (1.9.0.6240) by AlliedModders LLC
  13 "API: Particle Manager" (1.6) by hlstriker
  14 "Admin Help" (1.9.0.6240) by AlliedModders LLC
  15 "RandomCycle" (1.9.0.6240) by AlliedModders LLC
  16 "API: Database Bridge" (1.2) by hlstriker
  17 "Show Spectators" (1.5) by hlstriker
  18 "Grenades For Course" (2.0) by hlstriker
  19 "Disable Player Damage" (1.3) by hlstriker
  20 "Map Ratings" (1.0) by hlstriker
  21 "Bhop Cap" (1.0) by hlstriker
  22 "Sound Commands" (1.9.0.6240) by AlliedModders LLC
  23 "Dynamic" (0.0.32) by Neuro Toxin
  24 "Measure Gap" (1.3) by Hymns For Disco
  25 "Fun Votes" (1.9.0.6240) by AlliedModders LLC
  26 "Client Preferences" (1.9.0.6240) by AlliedModders LLC
  27 "API: Database User Stats" (1.10) by hlstriker
  28 "Reserved Slots" (1.9.0.6240) by AlliedModders LLC
  29 "Basic Commands" (1.9.0.6240) by AlliedModders LLC
  30 "API: Database Maps" (1.5) by hlstriker
  31 "Basic Votes" (1.9.0.6240) by AlliedModders LLC
  32 "API: Zone Manager" (1.17) by hlstriker
  33 "Zone Type: Blockade" (1.1) by hlstriker
  34 "API: Movement Styles" (1.12) by hlstriker
  35 "Client Air Accelerate" (1.2) by hlstriker
  36 "Basic Comm Control" (1.9.0.6240) by AlliedModders LLC
  37 "Zone Type: Respawn" (1.3) by hlstriker
  38 "Zone Type: Flashlight" (1.0) by hlstriker
  40 "API: User Logs" (1.1) by hlstriker
  41 "API: Client Times" (1.4) by hlstriker
  42 "Admin Menu" (1.9.0.6240) by AlliedModders LLC
  43 "Basic Chat" (1.9.0.6240) by AlliedModders LLC
  44 "API: Database Core" (1.5) by hlstriker
  55 "Zone Type: Weapon Strip" (1.0) by RussianLightning
  56 "Zone Type: Kill" (1.0) by hlstriker
  57 "API: Map Cookies" (1.0) by hlstriker
  58 "SQL Admin Manager" (1.9.0.6240) by AlliedModders LLC
  59 "API: Client Settings" (1.0) by hlstriker
  60 "API: Database Users" (1.5) by hlstriker
  61 "API: Database Username Stats" (1.3) by hlstriker
  62 "Game_Player_Equip Fix" (1.1.1) by Mitch
  63 "Player Commands" (1.9.0.6240) by AlliedModders LLC

**Comment by hlstriker** [comment]
In your database there should be a table called "plugin_zonemanager_data". Did you manually create this table or did you let the plugin create it?

Also, does this error happen on every map or just a certain one?

**Comment by lilgay** [comment]
At start i tought every module is hooked up to Database_Core so i just inserted manualy them in the  db what i called servers. And some plugins like core_users generates data. And some in the db called bridge. 

So that mean i should add for every plugin what has sql table add entery for it in the databse.cfg? And i just tried this. Deleted plugin table, added in the database.cfg and restarted server. Same msg and plugin didn't generate a table. And yes i  tested this more than in one map same for all.

**Comment by hlstriker** [comment]
Make 2 new databases:
1) testing_bridge
2) testing_servers

Run the following queries for each database:
- Bridge: https://pastebin.com/raw/wmYWBLyg
- Servers: https://pastebin.com/raw/mMvNuUsj

Open "csgo/cfg/swoobles/database_servers.cfg":
- Change "sm_database_servers_code" to "testcode".

Open "csgo/addons/sourcemod/configs/databases.cfg":
- Make sure sure you have the following entries but use your host/username/password.
- https://pastebin.com/raw/tuPJrFer

**Comment by lilgay** [comment]
Sorry for lack answering i was busy with some other things. You helped me too much today allready. It's works like charm now expect still i got this one error when i try to compile zone types from Speedruns folder. Not really nessery but would be nice in offline test out if make an style to see how fast i can finnish maps.   MPlugins-master\_SourceMod 1.6 Compiler\ZoneType_Timer_End.sp(2) : fatal error 120: cannot read from file: "../../../Libraries/ZoneManager/zone_manager" . I hope i didn't ask too much dumb questions.

**Comment by hlstriker** [comment]
Make sure you leave all the files in the directories they came in from the zip.

You should have this directory structure:
- "SMPlugins-master/Mods/SpeedRuns/ZoneTypes/ZoneType_Timer_End.sp"
- "SMPlugins-master/Libraries/ZoneManager/zone_manager.inc"

**Comment by lilgay** [comment]
I doubled checked everything is in right places.   I can compile API_ZoneManager with no problems
SourcePawn Compiler 1.6.4-dev+4625
Copyright (c) 1997-2006, ITB CompuPhase, (C)2004-2008 AlliedModders, LLC

Header size:           7300 bytes
Code size:            75912 bytes
Data size:            78212 bytes
Stack/heap size:      16384 bytes; Total requirements:  177808 bytes
Press ENTER to exit...

**Comment by hlstriker** [comment]
I'm not too sure then. Using a fresh download of this repo I can compile ZoneType_Timer_End.sp just fine.

**Comment by lilgay** [comment]
Can you host somewhere \Mods\SpeedRuns\ZoneTypes .smx for me i think they should work just fine in the server but i don't really understand reason why it's can compile  Zonemaker api but not those files. Anyway if u don't have time thanks for help so far. I just can't figure it at all problem with this.

**Comment by hlstriker** [comment]
https://swoobles.com/misc/ZoneTypes.zip

**Comment by lilgay** [comment]
Now all works just fine. Thanks!
