### ISSUE TITLE
zonemanager question.

### ISSUE THREAD

**Issue by lilgay** [hlstriker/SMPlugins#69]
Hey hlstriker could u show example of any map how do you setup stages right bit confusing this is very last question from me :p. Cuz i get alot this  error like this  - [API_ClientCookies.smx] Invalid cookie type -1 [SpeedRuns_Experience.smx]

**Comment by hlstriker** [comment]
You probably have to set the speedruns_group_name cvar.
Ex: speedruns_group_name "surf"

Here are the different types you can use:
https://github.com/hlstriker/SMPlugins/blob/471f8d75627f4a168b8561b2515bf1950525cb23/Mods/SpeedRuns/SpeedRuns_Experience.sp#L124

**Comment by lilgay** [comment]
And as i understand You make Timer Start set id to 1 And End Set to id 1  that makes 1 Stage and what about  Final End?

**Comment by hlstriker** [comment]
Final end is used to mark the very last stage of the map.

**Comment by lilgay** [comment]
That i understand.  That with stages at finnish shows  stage recordsc and map record. But when map is small and i need to use only 1 stage at end doesn't need to show map record? Or its supposted to show with Timer Start 1  and Timer End 1  stage  1 record only?

**Comment by hlstriker** [comment]
I'm not exactly sure what you're trying to ask, but you want to set the final end even if the map is only 1 stage long.

**Comment by lilgay** [comment]
Never mind.  When i had only 1 stage in map with Timer Start and Timer End it showed at   end in chat - Stage 1 Record after server Restart Map Record. And Reason why i couldn't compile before  Zone Timer type  was that plugin had different location  not like in github repo ../../../Libraries/FILE/FILE  but it should be ../../Libraries/FILE/FILE

Thanks i don't have really anymore questions about how it's works some things were bit too confusing  at start.
