### ISSUE TITLE
TimedMuteGag.sp compile logs

### ISSUE THREAD

**Issue by lazhoroni** [hlstriker/SMPlugins#76]
//// TimedMuteGag.sp
//
// C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\TimedMuteGag.sp(23) : warning 234: symbol "FCVAR_PLUGIN" is marked as deprecated: No logic using this flag ever existed in a released game. It only ever appeared in the first hl2sdk.
//
//
// C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\TimedMuteGag.sp(148) : warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthId
//
//
// C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\TimedMuteGag.sp(158) : warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthId
//
//
// C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\TimedMuteGag.sp(209) : warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthId
//
//
// C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\TimedMuteGag.sp(219) : warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthId
//
//
// C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\TimedMuteGag.sp(270) : warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthId
//
//
// C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\TimedMuteGag.sp(280) : warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthId
//
//
// C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\TimedMuteGag.sp(326) : warning 213: tag mismatch
// C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\TimedMuteGag.sp(353) : warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthId
//
//
// C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\TimedMuteGag.sp(363) : warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthId
//
//
// C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\TimedMuteGag.sp(447) : warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthId
//
//
// C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\TimedMuteGag.sp(457) : warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthId
//
//
// C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\TimedMuteGag.sp(541) : warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthId
//
//
// C:\Users\User\Desktop\sourcemod++\addons\sourcemod\scripting\TimedMuteGag.sp(551) : warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthId
//
//
// Code size:            16632 bytes
// Data size:             7196 bytes
// Stack/heap size:      16384 bytes
// Total requirements:   40212 bytes
//
// 14 Warnings.
//
// Compilation Time: 0,34 sec
// ----------------------------------------

**Comment by hlstriker** [comment]
This entire repo is to be compiled using the 1.6 compiler since everything here is written using the old syntax.

https://github.com/hlstriker/SMPlugins/tree/master/_SourceMod%201.6%20Compiler
